### ISSUE TITLE
allow a text property to be the highlight

### ISSUE THREAD

**Issue by chas-iot** [flatsiedatsie/highlights#1]
I'm not sure if this is even possible... For the two add-ons that I published, it would be good if a text property could be the Highlight. 
- For the [calendar addon](https://github.com/chas-iot/calendar), it would be good to have the Description (containing the holiday or event name) as the property shown on the Things page.
- For the [Pollutant Standards Index addon](https://github.com/chas-iot/psi-sg), it would be good to have the PSI Air Quality Indicator as the property shown on the Things page.

**Comment by flatsiedatsie** [comment]
I feel your pain. Unfortunately, there is [no capability](https://iot.mozilla.org/schemas/) to give text a center stage, so this addon cannot force a property into that role.
